In [2]:
#Sihao Ren // sren03 // 947105531
using Flux


In [5]:
weights = rand(2*19,19)
bias = rand(2*19)
a = Dense(weights, bias, sigmoid)
model = Chain(a, Dense(2*19, 2), softmax)

Chain(
  Dense(19, 38, σ),                     # 760 parameters
  Dense(38, 2),                         # 78 parameters
  NNlib.softmax,
)                   # Total: 4 arrays, 838 parameters, 6.492 KiB.

In [9]:
a = zeros(50)

50-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [16]:
a = [1,2,3]
a ./2

3-element Vector{Float64}:
 0.5
 1.0
 1.5

In [17]:
a

3-element Vector{Int64}:
 1
 2
 3