In [2]:
x = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
x = [1 2;3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [4]:
x.+1

2×2 Matrix{Int64}:
 2  3
 4  5

In [5]:
using Flux: gradient
f(x) = 3x^2 + 2x + 1

f (generic function with 1 method)

In [6]:
df(x) = gradient(f,x)[1]

df (generic function with 1 method)

In [7]:
df(5)

32.0

In [8]:
ddf(x) = gradient(df,x)

ddf (generic function with 1 method)

In [9]:
ddf(5)[1]

6.0

In [10]:
mysin(x) = sum((-1)^k*x^(1+2k)/factorial(1+2k) for k in 0:5)


mysin (generic function with 1 method)

In [11]:
x = 0.5

0.5

In [12]:
mysin(x), gradient(mysin, x)

(0.4794255386041834, (0.8775825618898637,))

In [13]:
sin(x), cos(x)

(0.479425538604203, 0.8775825618903728)

In [14]:
myloss(W,b, x) = sum(W*x .+ b)

myloss (generic function with 1 method)

In [15]:
W = randn(3,5)
b = zeros(3)
x = rand(5)

5-element Vector{Float64}:
 0.8317170120379539
 0.8076642555838891
 0.8366787852855462
 0.14103722835996957
 0.5681556374288682

In [16]:
gradient(myloss, W, b, x)

([0.8317170120379539 0.8076642555838891 … 0.14103722835996957 0.5681556374288682; 0.8317170120379539 0.8076642555838891 … 0.14103722835996957 0.5681556374288682; 0.8317170120379539 0.8076642555838891 … 0.14103722835996957 0.5681556374288682], Fill(1.0, 3), [-3.145543747662095, -0.32133048761957983, -1.2200662782385534, 0.3116566387369154, -1.116411033860243])

In [17]:
using Flux

In [18]:
m  = Dense(10, 5)

Dense(10, 5)        # 55 parameters

In [19]:
params(m)

Params([Float32[0.34532592 -0.39208692 … 0.574553 0.061624736; -0.26492614 -0.11973269 … -0.48048463 0.5819501; … ; 0.0063448306 -0.53100723 … 0.20167212 -0.5222888; 0.32225737 -0.23173857 … -0.04732902 -0.22965881], Float32[0.0, 0.0, 0.0, 0.0, 0.0]])

In [20]:
x= rand(Float32, 10)

10-element Vector{Float32}:
 0.9074971
 0.010169089
 0.39643282
 0.21169585
 0.7492923
 0.44820553
 0.31829786
 0.3686636
 0.34601384
 0.4968204

In [21]:
m = Chain(Dense(10,5,relu), Dense(5,2), softmax)
l(x) = Flux.Losses.crossentropy(m(x), [0.5, 0.5])

l (generic function with 1 method)

In [22]:
grads = gradient(params(m)) do 
    l(x)
end
for p in params(m)
    println(p, grads[p])
end

Float32[0.4746044 -0.34222674 -0.45046917 -0.090394855 0.32355085 -0.49125144 -0.6234648 0.37760136 -0.3835531 -0.082963586; -0.6258807 -0.26420695 0.15352778 0.2410216 -0.6096261 -0.38510802 0.32458532 0.4021931 0.481807 0.30377507; -0.43860996 -0.21838242 -0.1937002 -0.24038602 -0.20494726 -0.023404587 -0.48110983 0.31607267 0.2727312 0.23850282; -0.5497265 -0.58539546 -0.022729127 -0.34721026 0.28367564 -0.62921834 -0.08812382 0.35094145 -0.19293584 -0.070555225; -0.0017755423 -0.10343163 0.21553952 0.20281616 0.44874066 0.07364806 -0.49248618 0.15219262 -0.21039912 0.36557585]Float32[0.016431669 0.00018412742 0.0071780425 0.0038330879 0.013567121 0.0081154695 0.005763286 0.006675237 0.006265127 0.008995718; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0; -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0; 0.03474611 0.00038935253 0.015178559 0.008105379 0.02868879 0.017160825 0.01218694 0.014115336 0.013248125 0.019022183]
Float32[0.0, 0.0, 0.0, 0.0

In [24]:
using Flux.Optimise: update!, Descent
η = 0.1

0.1

In [25]:
for p in params(m)
    update!(p, η*grads[p])
end

In [26]:
opt = Descent(0.01)

Descent(0.01)

In [27]:
data, labels = rand(10, 100), fill(0.5, 2, 100)
loss(x, y) = Flux.Losses.crossentropy(m(x), y)
Flux.train!(loss, params(m), [(data,labels)], opt)


In [28]:
using Statistics
using Flux, Flux.Optimise
using MLDatasets: CIFAR10
using Images.ImageCore
using Flux: onehotbatch, onecold
using Base.Iterators: partition
using CUDA

ArgumentError: ArgumentError: Package MLDatasets not found in current path:
- Run `import Pkg; Pkg.add("MLDatasets")` to install the MLDatasets package.
